### ISSUE TITLE
Leetcode Problem - Number of Dice Rolls With Target Sum

### ISSUE THREAD

**Issue by sankave00** [RIKI-05/RIKI-05-Beginner-Friendly#11]
I would like to contribute to this repo by giving solution to a leetcode medium problem.
This a DP problem named number of ways to get dice rolls given a target sum
I would like to give the solution for this, hope you will assign the issue to me and add the hacktoberfest tag
Thank you

**Comment by RIKI-05** [comment]
@sankave00 go ahead... happy coding

**Comment by sankave00** [comment]
> @sankave00 go ahead... happy coding

I have given a PR #12 ..thank you
